[book]
authors = ["OGBot"]
language = "en"
multilingual = false
src = "src"
title = "Large Language Models: From Zero to Hero"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"

[preprocessor.quiz]
command = "mdbook-quiz"
